sudo: required
dist: xenial
language: cpp
cache:
  - apt
  - directories:
    - Package

compiler:
  - g++
#jdk: oraclejdk7
os:
  - unix
addons:
  ssh_known_hosts:
    - github.com
    - frs.sourceforge.net

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE"
    
  matrix:
    # DOWNLOAD_QT:
    #     APT: Use apt to install from ubuntu source;
    #     TRUE: download from download.qt.io
    #     FALSE: install from https://launchpad.net/~beineri
    - BUILD_TARGERT="unix" DOWNLOAD_QT=APT
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 DOWNLOAD_QT=FALSE
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 DOWNLOAD_QT=FALSE STATIC=ON

    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.10 DOWNLOAD_QT=TRUE
    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.9 QT_VERSION=5.9.9 DOWNLOAD_QT=TRUE STATIC=ON

    # BUILD_ARCH qt 大于等于 5.14.0 可选（arm64-v8a armeabi-v7a x86_64 x86）组合
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_API=android-24 ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.9 QT_VERSION=5.9.9 DOWNLOAD_QT=TRUE
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_API=android-24 ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.12 QT_VERSION=5.12.10 DOWNLOAD_QT=TRUE
    - BUILD_TARGERT="android" BUILD_ARCH="x86" ANDROID_API=android-24 QT_VERSION_DIR=5.12 QT_VERSION=5.12.10 DOWNLOAD_QT=TRUE

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v0.5.7"

install:
  - cd ${SOURCE_DIR}
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh > /dev/null
#  - |
#    if [ "$BUILD_TARGERT"="unix" -a -z "$RABBIT_ARCH" ]; then
#        source /opt/qt511/bin/qt511-env.sh
#    fi

before_script:
  - cd ${SOURCE_DIR}

script:
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

after_script:
#  - "xpra stop :99"

#after_success:
  #- |
    #wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    #chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    #export VERSION="v0.5.7"
    #./linuxdeployqt-continuous-x86_64.AppImage debian/serialportassistant/opt/SerialPortAssistant/share/applications/*.desktop -appimage

    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    #bash upload.sh Serial*.AppImage*

#branches:
#  except:
#    - # Do not build tags that we create when we upload to GitHub Releases
#    - /^(?i:continuous)$/

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

#deploy:
#  - provider: releases
#    api_key:
#      secure: nYf7nWTSp5PnEow6DjKwiJJwhsdJTqFZd9KlvxFC7QOjsRyHtzpXM2SDK1BavOws/gK0GxtjYfpt2f4GTuQJvDB3mJsn4OKvVGlkKtBFhTNDMVZjehhbgvmeivvtQ+NI8gbQtkI29oXes0ToKqvUV94WL5wRJwcUnfFvinJmxIHhlfQ3/nf9C1KAgFQ2oAiWCj+pOj54LEdEfBnqZfbpBvalwW4PWPB4lBLFvQpyNJhdcxHrl8Cvo8qfq07glPNoD4HLFaGhAQ+hxCcoC5cgrQxsGu9sVyHgHXj0a3BV520Aa946WrR4P0yHQnECH169WY4ZzPcpZjJyd0l+gC37sggAjQsXw+LwLOB/uFY7Ipg8xquHIYPDC8UUdfPBVcd0aJ+u7Mb7CUUnwCZ1gL/w1oi1TFyEJcCp/HznparCQAdiyaX6BBXghxKAYRWMBDGvFAx5gZv2OaocRIOdGLAIXGL43vLKbuLjNj2syLB2GzG5uPaOgaZQyYlIhd/iU6r55Ih2XMCGsTOwCOSy+Y1+ULGBoP7ZE8AuVlHxn9MZQoZg24IVqlXgIr/bEtcSwIi0wCKfjvsD3TjMSwAr6stilhHmJ6ldB9B+TAX6TdxB/NUDDxaxG2ZoYXOWOanBv02FYc/Opbq8WA3vv6AlE+FAqOtdcc8ULBC4rz8Q8UOro6U=
#    file: $TRAVIS_BUILD_DIR/../serialportassistant_*_amd64.deb
#    skip_cleanup: true
#    #draft: true
#    on:
#      tags: true
#      condition: "$BUILD_TARGERT=unix && FALSE=$DOWNLOAD_QT"
