# https://snapcraft.io/docs/the-snap-format
# How Snapcraft builds snaps: https://snapcraft.io/docs/how-snapcraft-builds
# Snapcraft.yaml schema: https://documentation.ubuntu.com/snapcraft/stable/reference/project-file/snapcraft-yaml

name: serialportassistant
title: Serial Port Assistant
version: '0.5.34-dev'
type: app
license: GPL-3.0+
contact: kl222@126.com
donation:
  - https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png
issues: https://github.com/KangLin/SerialPortAssistant/issues
summary: Serial Port Assistant # 79 char long summary
description: |
  Serial Port Assistant
  .
  Author: Kang Lin <kl222@126.com>
  .
  Donation:
  .
  https://github.com/KangLin/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitee.com/kl222/RabbitCommon/raw/master/Src/Resource/image/Contribute.png
  .
  https://gitlab.com/kl222/RabbitCommon/-/raw/master/Src/Resource/image/Contribute.png

# See: https://snapcraft.io/docs/reference-architectures
# See: https://snapcraft.io/docs/architectures
base: core24 # the base snap is the execution environment for this snap
# - devel
# - stable
grade: stable # must be 'stable' to release into candidate/stable channels
# Confinement levels: https://snapcraft.io/docs/classic-confinement#heading--levels
# Classic confinement: https://snapcraft.io/docs/classic-confinement
# - devmode
# - strict
confinement: strict # use 'strict' once you have the right plugs and slots

# lifecycle: https://snapcraft.io/docs/parts-lifecycle
# Iterating over a build: https://snapcraft.io/docs/iterating-over-a-build
# Part directives: https://snapcraft.io/docs/snapcraft-yaml-schema#part-directives
parts:
  rabbitcommon:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: dump # See: https://snapcraft.io/docs/dump-plugin
    source: https://github.com/KangLin/RabbitCommon.git
    source-type: git
    source-branch: master
    source-depth: 1
    organize:
      '*': RabbitCommon/
    prime:
      - -*

  serialportassistant:
    # see: https://snapcraft.io/docs/supported-plugins
    # See 'snapcraft plugins'
    plugin: cmake # See: https://snapcraft.io/docs/cmake-plugin
    source: .
    after:
      - rabbitcommon
    build-packages:
      - libcmark-dev
      - cmark
      - libssl-dev
      - libcrypt-dev
      - libpulse-dev
      - pulseaudio-dev
    stage-packages:
      - libcmark0.30.2
      - libopengl0
      - libgl1
      - libglx0
      - libglu1-mesa
      - libssl3
      - libcrypt1
      - zlib1g
      - libpulse0
      - pulseaudio
    cmake-parameters:
      # See: https://snapcraft.io/docs/parts-environment-variables
      - -DRabbitCommon_ROOT=$CRAFT_STAGE/RabbitCommon/
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr/local/
    # See: https://snapcraft.io/docs/overrides
    override-stage: |
      cd $CRAFT_PART_INSTALL/usr/local/bin
      #  if [ ! -f serialportassistant ]; then
      #      ln -s SerialPortAssistant serialportassistant
      #  fi
      sed -i 's|Icon=io\.github\.KangLin\.SerialPortAssistant|Icon=/usr/local/share/pixmaps/io\.github\.KangLin\.SerialPortAssistant\.png|' $CRAFT_PART_INSTALL/usr/local/share/applications/io.github.KangLin.SerialPortAssistant.desktop
      sed -i 's|Path=/usr/local/bin|Path=\$\{SNAP\}/usr/local/bin|' $CRAFT_PART_INSTALL/usr/local/share/applications/io.github.KangLin.SerialPortAssistant.desktop
      snapcraftctl stage
    prime:
     - -usr/bin/cmark
     - -usr/local/bin/cmark
     - -usr/local/include
     - -usr/local/lib/cmake
     - -usr/local/lib/pkgconfig
     - -usr/local/lib/*.a

# App directives: https://snapcraft.io/docs/snapcraft-yaml-schema#app-directives
apps:
 serialportassistant:
   command: usr/local/bin/SerialPortAssistant
   # See: https://snapcraft.io/docs/desktop-menu-support#heading--desktop-key
   desktop: usr/local/share/applications/io.github.KangLin.SerialPortAssistant.desktop
   environment:
     LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
     #QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt6/plugins/
     PATH: $SNAP/usr/local/bin:$PATH
   # List extensions, run `snapcraft extensions`
   extensions:
     - kde-neon-6
   # See: https://snapcraft.io/docs/supported-interfaces
   plugs:
     - network
     - network-status
     - network-control
     - network-bind
     - network-manager
     - opengl
     - serial-port
     - home
