name: ubuntu

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [Ubuntu-20.04, Ubuntu-18.04]

    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    runs-on: ${{ matrix.os }}
    env:
      SerialPortAssistant_VERSION: 0.5.9

    steps:
    - uses: actions/checkout@v2

    - name: apt helper action
      uses: ryankurte/action-apt@v0.2.0
      with:
        # architectures to pass to dpkg --add-architecture
        #architectures: # optional
        # apt packages to install
        packages: xvfb xpra debhelper fakeroot qttools5-dev qttools5-dev-tools libqt5serialport5-dev qtbase5-dev qtbase5-dev-tools

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: git clone RabbitCommon
      working-directory: ${{github.workspace}}
      run: git clone https://github.com/KangLin/RabbitCommon.git

    - name: build SerialPortAssistant
      env:
        RabbitCommon_DIR: ${{github.workspace}}/RabbitCommon
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: |
        cd ${{github.workspace}}
        ./build_debpackage.sh
        cp ../serialportassistant_${{env.SerialPortAssistant_VERSION}}_amd64.deb serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb

    - name: Install deb
      run: |
        sudo Xvfb :99 -ac &
        export DISPLAY=:99.0
        sudo dpkg -i serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb
        echo "test ......"
        ./test/test_linux.sh

    #- name: Install deb
    #  run: |
        # MD5=`md5sum serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb | awk '{print $1}'`
        # /opt/SerialPortAssistant/bin/SerialPortAssistant \
        #        -f "`pwd`/update_linux.xml" \
        #        --md5 ${MD5} \
        #        -m "${{env.SerialPortAssistant_VERSION}}" \
        #        --url "https://github.com/KangLin/SerialPortAssistant/releases/download/${VERSION}/serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb"

    #- name: Generate appimage
    #  run: |
    #    cd debian/serialportassistant/opt
    #    URL_LINUXDEPLOYQT=https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    #    wget -c -nv ${URL_LINUXDEPLOYQT} -O linuxdeployqt.AppImage
    #    chmod a+x linuxdeployqt.AppImage
    #    cd SerialPortAssistant
    #    ../linuxdeployqt.AppImage share/applications/*.desktop \
    #          -qmake=qmake -appimage -verbose
    #    cp SerialPort_Assistant-${VERSION}-x86_64.AppImage ${{github.workspace}}/.

    - name: Upload To Github Release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        #prerelease: true
        body: |
          [:cn: 修改日志](ChangeLog_zh_CN.md) [:us: Change log](ChangeLog.md)
        files: |
          serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb
          
    - name: update
      uses: actions/upload-artifact@v2
      with:
        name: SerialPortAssistant_${{env.SerialPortAssistant_VERSION}}_${{ matrix.os }}
        path: |
          serialportassistant_${{env.SerialPortAssistant_VERSION}}_${{matrix.os}}_amd64.deb

